[package]
name = "valveflow"
description = "Everything you need to work with Valve's Source Engine files"
version = "0.1.0"
repository = "https://github.com/lasa01/valveflow"
readme = "README.md"
keywords = ["valve", "source", "vdf", "vmf", "vmt"]
categories = ["parser-implementations"]
authors = ["Lassi Säike"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["fs", "steam", "vmf", "vpk", "vmt"]
steam = ["winreg", "home", "phf"]
vpk = ["zerocopy", "byteorder", "crc", "md5"]
fs = ["vpk"]
vmt = ["fs", "vtflib", "image"]
vmf = ["fs", "vmt"]

[dependencies]
approx = "0.4.0"
bytecount = "0.6.2"
byteorder = { version = "1.4.3", optional = true }
crc = { version = "1.8.1", optional = true }
derive_more = "0.99.13"
float-ord = "0.3.1"
itertools = "0.10.0"
md5 = { version = "0.7.0", optional = true }
nalgebra = "0.24.1"
ndarray = "0.14.0"
nom = "6.1.2"
rgb = "0.8.27"
serde = { git = "https://github.com/lasa01/serde", branch = "case-insensitive-attr" }
serde_derive = { git = "https://github.com/lasa01/serde", branch = "case-insensitive-attr" }
thiserror = "1.0.24"
uncased = { version = "0.9.6", features = ["with-serde-alloc"] }
zerocopy = { version = "0.5.0", optional = true }
phf = { version = "0.8.0", features = ["macros"], optional = true }
vtflib = { version = "0.2.0", optional = true, features = ["static"] }
image = { version = "0.23.14", optional = true, default-features = false }

[target.'cfg(windows)'.dependencies]
winreg = { version = "0.8", optional = true }

[target.'cfg(not(windows))'.dependencies]
home = { version = "0.5.3", optional = true }

[dev-dependencies]
maplit = "1.0.2"

[patch.crates-io]
serde = { git = "https://github.com/lasa01/serde", branch = "case-insensitive-attr" }
serde_derive = { git = "https://github.com/lasa01/serde", branch = "case-insensitive-attr" }
