[package]
name = "valveflow"
description = "Everything you need to work with Valve's Source Engine files"
version = "0.1.0"
repository = "https://github.com/lasa01/valveflow"
readme = "README.md"
keywords = ["valve", "source", "vdf", "vmf", "vmt"]
categories = ["parser-implementations"]
authors = ["Lassi Säike"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["vmf"]
vmf = []

[dependencies]
bytecount = "0.6.2"
derive_more = "0.99.13"
itertools = "0.10.0"
nalgebra = "0.24.1"
ndarray = "0.14.0"
nom = "6.1.2"
rgb = "0.8.27"
serde = { git = "https://github.com/lasa01/serde", branch = "case-insensitive-attr" }
serde_derive = { git = "https://github.com/lasa01/serde", branch = "case-insensitive-attr" }
thiserror = "1.0.24"
uncased = { version = "0.9.6", features = ["with-serde-alloc"] }

[dev-dependencies]
maplit = "1.0.2"

[patch.crates-io]
serde = { git = "https://github.com/lasa01/serde", branch = "case-insensitive-attr" }
serde_derive = { git = "https://github.com/lasa01/serde", branch = "case-insensitive-attr" }
